//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaExampleControllers
{
    [Serializable]
    public class JointPositionsMsg : Message
    {
        public const string k_RosMessageName = "franka_example_controllers/JointPositions";
        public override string RosMessageName => k_RosMessageName;

        public double[] positions;

        public JointPositionsMsg()
        {
            this.positions = new double[7];
        }

        public JointPositionsMsg(double[] positions)
        {
            this.positions = positions;
        }

        public static JointPositionsMsg Deserialize(MessageDeserializer deserializer) => new JointPositionsMsg(deserializer);

        private JointPositionsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.positions);
        }

        public override string ToString()
        {
            return "JointPositionsMsg: " +
            "\npositions: " + System.String.Join(", ", positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
